# Generated by Django 5.2 on 2025-04-06 14:17

import django.db.models.deletion
import wallet.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.SmallIntegerField(choices=[(wallet.models.Color['RED'], '#ff0000'), (wallet.models.Color['BLUE'], '#0000ff'), (wallet.models.Color['YELLOW'], '#ffff00'), (wallet.models.Color['GREEN'], '#009933'), (wallet.models.Color['PURPLE'], '#660066'), (wallet.models.Color['BLACK'], '#000000'), (wallet.models.Color['ORANGE'], '#ff9900'), (wallet.models.Color['PINK'], '#ff6699'), (wallet.models.Color['LIGHT_BLUE'], '#66ccff'), (wallet.models.Color['GRAY'], '#595959')])),
                ('category_type', models.SmallIntegerField(choices=[(wallet.models.CategoryType['INCOME'], 'Доход'), (wallet.models.CategoryType['OUTCOME'], 'Расход')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
